export type TrailDifficulty = "Easy" | "Moderate" | "Hard";
export type TrailTerrain = "woodland" | "hill" | "mountain" | "coastal" | "road" | "mixed";
export type TrailRouteType = "loop" | "out-and-back" | "point-to-point";
export type TrailBestFor = "training" | "family walk" | "summit prep" | "scenic walk";
export type TrailBenefit = "cardio" | "elevation" | "endurance" | "pack weight";
export type TrailRegion =
  | "Scottish Highlands"
  | "Lake District"
  | "Peak District"
  | "Snowdonia"
  | "Yorkshire Dales"
  | "Brecon Beacons"
  | "Isle of Skye"
  | "Cairngorms"
  | "Ireland";

export interface Trail {
  id: string;
  name: string;
  location: string;
  region?: TrailRegion;
  distance: number;
  elevationGain: number;
  estimatedTime: string;
  difficulty: TrailDifficulty;
  terrain: TrailTerrain;
  routeType: TrailRouteType;
  bestFor: TrailBestFor[];
  description: string;
  trainingBenefits: TrailBenefit[];
  emoji: string;
  lat?: number;
  lng?: number;
  isCustom?: boolean;
  notes?: string;
  createdAt?: string;
}

export const CURATED_HILLS: Trail[] = [
  {
    id: "h001",
    name: "Ben Nevis",
    location: "Fort William, Scotland",
    region: "Scottish Highlands",
    distance: 17.4,
    elevationGain: 1340,
    estimatedTime: "7h 30m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "out-and-back",
    bestFor: ["summit prep", "training"],
    description:
      "The highest peak in the British Isles at 1,345m. The Mountain Track (Tourist Route) starts from Glen Nevis and follows a well-worn zigzag path to the broad, rocky plateau. Deceptively demanding — the upper mountain is often in cloud and temperature can drop sharply year-round. A genuine mountain day requiring full kit and navigation skills.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🏔️",
    lat: 56.7969,
    lng: -5.0035,
  },
  {
    id: "h002",
    name: "Snowdon via Pyg Track",
    location: "Snowdonia, Wales",
    region: "Snowdonia",
    distance: 11.5,
    elevationGain: 900,
    estimatedTime: "5h 30m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "out-and-back",
    bestFor: ["summit prep", "training"],
    description:
      "The Pyg Track is the most dramatic approach to Snowdon's 1,085m summit — Wales's highest peak. The route starts from Pen-y-Pass and traverses rocky ridgeline with exposure to Glaslyn below. The final ascent scrambles over boulders to the crowded summit. Excellent altitude training that closely mimics bigger alpine objectives.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    lat: 53.0685,
    lng: -4.0763,
  },
  {
    id: "h003",
    name: "Scafell Pike",
    location: "Lake District, Cumbria",
    region: "Lake District",
    distance: 13.8,
    elevationGain: 950,
    estimatedTime: "6h 00m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "loop",
    bestFor: ["summit prep", "training"],
    description:
      "England's highest peak at 978m, ascended via the classic Corridor Route from Seathwaite. The boulder-strewn upper mountain demands good footing and confidence in poor visibility. A loop via Lingmell and Piers Gill adds dramatic scenery. One of the most physically demanding days in the Lake District.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🏔️",
    lat: 54.4541,
    lng: -3.2116,
  },
  {
    id: "h004",
    name: "Helvellyn via Striding Edge",
    location: "Lake District, Cumbria",
    region: "Lake District",
    distance: 14.4,
    elevationGain: 760,
    estimatedTime: "6h 00m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "loop",
    bestFor: ["summit prep", "training"],
    description:
      "One of England's great mountain days — the approach via Striding Edge is a narrow, exposed rocky arête demanding sure footing and confidence. The horseshoe return via Swirral Edge completes the circuit. Helvellyn at 950m offers spectacular views over the Eastern Fells. Perfect preparation for scrambling and alpine routes.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "⛰️",
    lat: 54.5279,
    lng: -3.0160,
  },
  {
    id: "h005",
    name: "Cat Bells",
    location: "Keswick, Lake District, Cumbria",
    region: "Lake District",
    distance: 7.1,
    elevationGain: 450,
    estimatedTime: "2h 45m",
    difficulty: "Easy",
    terrain: "mountain",
    routeType: "loop",
    bestFor: ["training", "family walk", "scenic walk"],
    description:
      "Cat Bells is one of the Lake District's most loved fells — a compact 451m mountain above Derwentwater with a ridgeline walk that punches well above its height. The ascent from Hawse End is short but genuinely steep, making it ideal for elevation training without committing a full day. Superb views in all directions.",
    trainingBenefits: ["elevation", "cardio"],
    emoji: "🌿",
    lat: 54.5476,
    lng: -3.1678,
  },
  {
    id: "h006",
    name: "Pen y Fan South Ridge",
    location: "Brecon Beacons, Powys",
    region: "Brecon Beacons",
    distance: 9.8,
    elevationGain: 420,
    estimatedTime: "3h 30m",
    difficulty: "Moderate",
    terrain: "mountain",
    routeType: "out-and-back",
    bestFor: ["summit prep", "training"],
    description:
      "Pen y Fan at 886m is the highest peak in South Wales. The classic south ridge approach via Storey Arms follows a broad track before steepening near the summit plateau. A favourite of military and civilian athletes alike — infamous as a selection route. Unforgiving in bad weather, exhilarating in good.",
    trainingBenefits: ["elevation", "cardio", "endurance"],
    emoji: "🏔️",
    lat: 51.8839,
    lng: -3.4373,
  },
  {
    id: "h007",
    name: "Kinder Scout Circular",
    location: "Edale, Peak District, Derbyshire",
    region: "Peak District",
    distance: 14.2,
    elevationGain: 490,
    estimatedTime: "5h 30m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "loop",
    bestFor: ["summit prep", "training"],
    description:
      "Kinder Scout at 636m is the highest point in the Peak District — a vast dark plateau of peat moorland and gritstone edges. The circular from Edale takes in Jacob's Ladder, the plateau crossing, and the dramatic Kinder Downfall waterfall. Navigation across the featureless plateau is genuinely challenging in poor visibility.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🌫️",
    lat: 53.3867,
    lng: -1.8717,
  },
  {
    id: "h008",
    name: "Mam Tor & Great Ridge",
    location: "Castleton, Peak District, Derbyshire",
    region: "Peak District",
    distance: 8.4,
    elevationGain: 260,
    estimatedTime: "3h 00m",
    difficulty: "Moderate",
    terrain: "hill",
    routeType: "loop",
    bestFor: ["training", "scenic walk", "family walk"],
    description:
      "One of the Peak District's most iconic walks, following the dramatic Great Ridge from Mam Tor to Hollins Cross and back. Short enough for a quick training day, challenging enough to build real hill strength. Stunning views over Edale and the Hope Valley — and the crumbling road at Mam Nick is always good for a photo.",
    trainingBenefits: ["elevation", "cardio"],
    emoji: "⛰️",
    lat: 53.3521,
    lng: -1.8112,
  },
  {
    id: "h009",
    name: "Ingleborough",
    location: "Horton-in-Ribblesdale, Yorkshire Dales",
    region: "Yorkshire Dales",
    distance: 12.6,
    elevationGain: 460,
    estimatedTime: "4h 30m",
    difficulty: "Moderate",
    terrain: "hill",
    routeType: "loop",
    bestFor: ["training", "summit prep"],
    description:
      "Ingleborough at 723m is one of Yorkshire's iconic Three Peaks. The approach from Horton crosses limestone pavements before a steep pull to the flat, gritstone summit plateau. Exposed and demanding in poor conditions — the plateau section is often boggy and the wind relentless. Perfect training terrain for serious upland objectives.",
    trainingBenefits: ["elevation", "endurance", "cardio"],
    emoji: "⛰️",
    lat: 54.1770,
    lng: -2.3695,
  },
  {
    id: "h010",
    name: "Whernside",
    location: "Ribblehead, Yorkshire Dales",
    region: "Yorkshire Dales",
    distance: 12.4,
    elevationGain: 455,
    estimatedTime: "4h 00m",
    difficulty: "Moderate",
    terrain: "hill",
    routeType: "loop",
    bestFor: ["training", "scenic walk"],
    description:
      "Yorkshire's highest peak at 736m, approached from the spectacular Ribblehead Viaduct. The ridge walk offers long views across the Dales before the steep descent back to Ribblehead. The classic Three Peaks route includes all three in one day — Whernside alone is an excellent standalone training route with reliable paths.",
    trainingBenefits: ["elevation", "endurance", "cardio"],
    emoji: "🌾",
    lat: 54.2218,
    lng: -2.3967,
  },
  {
    id: "h011",
    name: "Old Man of Storr",
    location: "Portree, Isle of Skye, Scotland",
    region: "Isle of Skye",
    distance: 6.8,
    elevationGain: 380,
    estimatedTime: "3h 00m",
    difficulty: "Moderate",
    terrain: "mountain",
    routeType: "loop",
    bestFor: ["summit prep", "scenic walk"],
    description:
      "One of Scotland's most iconic landscapes — the surreal cluster of basalt pinnacles above the Sound of Raasay. The well-maintained path ascends steeply through forestry before opening to the dramatic Trotternish ridge. The terrain and sustained exposure make it excellent preparation for bigger mountain objectives. Views on a clear day are extraordinary.",
    trainingBenefits: ["elevation", "cardio"],
    emoji: "🗿",
    lat: 57.5092,
    lng: -6.1828,
  },
  {
    id: "h012",
    name: "Ben Lomond",
    location: "Rowardennan, Loch Lomond",
    region: "Scottish Highlands",
    distance: 12.0,
    elevationGain: 1010,
    estimatedTime: "5h 30m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "out-and-back",
    bestFor: ["summit prep", "training"],
    description:
      "The most southerly Munro at 974m and one of Scotland's most climbed mountains. The tourist path from Rowardennan is clear and well-maintained through forestry and open moorland before steepening dramatically on the final cone to the summit. Outstanding views over Loch Lomond and, on a good day, as far as Ben Nevis.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🏔️",
    lat: 56.1879,
    lng: -4.6335,
  },
  {
    id: "h013",
    name: "Cairn Gorm via Ptarmigan Ridge",
    location: "Aviemore, Cairngorms",
    region: "Cairngorms",
    distance: 11.2,
    elevationGain: 640,
    estimatedTime: "5h 00m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "loop",
    bestFor: ["summit prep", "training"],
    description:
      "Cairn Gorm at 1,245m is the fifth-highest peak in the UK, sitting on the vast arctic plateau of the Cairngorms. The ascent via the Ptarmigan Ridge from Coire Cas is serious mountain terrain — arctic conditions are possible in any month. Navigation skills and full winter kit are essential. Incomparable high-altitude training in the UK.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🏔️",
    lat: 57.1186,
    lng: -3.6435,
  },
  {
    id: "h014",
    name: "Croagh Patrick",
    location: "Westport, County Mayo, Ireland",
    region: "Ireland",
    distance: 7.8,
    elevationGain: 760,
    estimatedTime: "4h 00m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "out-and-back",
    bestFor: ["summit prep", "training"],
    description:
      "Ireland's holy mountain at 764m — a sharp quartzite cone rising above Clew Bay. The path is clear from the car park at Murrisk but the upper 300m is relentlessly steep and loose scree. The descent is harder than the ascent and demands careful footwork. An iconic Irish hill with views over hundreds of islands on a clear day.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🇮🇪",
    lat: 53.7612,
    lng: -9.6613,
  },
  {
    id: "h015",
    name: "Carrauntoohil",
    location: "Killarney, County Kerry, Ireland",
    region: "Ireland",
    distance: 11.4,
    elevationGain: 1040,
    estimatedTime: "6h 00m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "out-and-back",
    bestFor: ["summit prep", "training"],
    description:
      "Ireland's highest peak at 1,038m, accessed via the classic Devil's Ladder route from Cronin's Yard. The approach through the Hag's Glen is dramatic with two glacial loughs below the summit pyramid. The Devil's Ladder gully is eroded and requires care. The MacGillycuddy's Reeks ridge offers a serious extension for strong hill walkers.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🏔️",
    lat: 51.9996,
    lng: -9.7451,
  },
  {
    id: "h016",
    name: "Tryfan North Ridge",
    location: "Ogwen Valley, Snowdonia, Wales",
    region: "Snowdonia",
    distance: 6.2,
    elevationGain: 680,
    estimatedTime: "4h 00m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "out-and-back",
    bestFor: ["summit prep", "training"],
    description:
      "Tryfan at 915m is one of Wales's great mountains and the only 3,000ft peak in England and Wales that cannot be walked to the top — the summit requires a short scramble. The North Ridge is a classic Grade 1 scramble demanding hands-on progress throughout. An excellent introduction to mountain scrambling and essential prep for harder alpine terrain.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🧗",
    lat: 53.1003,
    lng: -3.9968,
  },
  {
    id: "h017",
    name: "Ben Macdui",
    location: "Cairngorms, Scotland",
    region: "Cairngorms",
    distance: 22.0,
    elevationGain: 1260,
    estimatedTime: "9h 00m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "out-and-back",
    bestFor: ["summit prep", "training"],
    description:
      "The UK's second-highest peak at 1,309m. Reached via a long approach across the Cairngorm plateau from Cairn Gorm summit — the high-level traverse crosses genuinely arctic terrain and demands reliable navigation. The distance and sustained altitude make this one of the finest high-mountain days in Britain. An essential Cairngorm objective.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🏔️",
    lat: 57.0703,
    lng: -3.6684,
  },
  {
    id: "h018",
    name: "Blencathra via Sharp Edge",
    location: "Threlkeld, Lake District, Cumbria",
    region: "Lake District",
    distance: 10.2,
    elevationGain: 640,
    estimatedTime: "4h 30m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "loop",
    bestFor: ["summit prep", "training"],
    description:
      "Sharp Edge is considered more technically demanding than Striding Edge on Helvellyn — a narrow, exposed arête with genuine exposure on both sides requiring hands-on scrambling. The summit of Blencathra at 868m gives spectacular views across the northern Lake District fells. The Hall's Fell descent is equally exhilarating. A serious mountain day.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "⚡",
    lat: 54.6350,
    lng: -3.0442,
  },
  {
    id: "h019",
    name: "Great Gable",
    location: "Wasdale Head, Lake District, Cumbria",
    region: "Lake District",
    distance: 11.6,
    elevationGain: 870,
    estimatedTime: "5h 00m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "loop",
    bestFor: ["summit prep", "training"],
    description:
      "Great Gable at 899m is one of the most celebrated mountains in England — an iconic pyramid visible from much of the Lake District. The approach from Wasdale Head is the most direct and dramatic, climbing steeply via the Breast Route. The rocky summit plateau and views over the Wasdale valley are exceptional. A genuine mountain challenge.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🗻",
    lat: 54.4828,
    lng: -3.2181,
  },
  {
    id: "h020",
    name: "Sca Fell & Scafell Pike Loop",
    location: "Wasdale Head, Lake District, Cumbria",
    region: "Lake District",
    distance: 16.4,
    elevationGain: 1150,
    estimatedTime: "7h 30m",
    difficulty: "Hard",
    terrain: "mountain",
    routeType: "loop",
    bestFor: ["summit prep", "training"],
    description:
      "The classic combination of England's highest two peaks in a single day. Taking in Scafell Pike (978m) and Sca Fell (964m) involves the exposed Lord's Rake and West Wall Traverse linking the two summits — serious scrambling terrain requiring confident movement on rock. One of the finest and most committing mountain days in England.",
    trainingBenefits: ["elevation", "endurance", "pack weight"],
    emoji: "🏔️",
    lat: 54.4497,
    lng: -3.2115,
  },
];
