export interface WainwrightFell {
  id: string;
  name: string;
  book: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  summitElevation: number;
  elevationGain: number;
}

export const WAINWRIGHT_BOOK_NAMES: Record<1 | 2 | 3 | 4 | 5 | 6 | 7, string> = {
  1: "Eastern Fells",
  2: "Far Eastern Fells",
  3: "Central Fells",
  4: "Southern Fells",
  5: "Northern Fells",
  6: "North Western Fells",
  7: "Western Fells",
};

export const WAINWRIGHT_BOOK_FELL_COUNTS: Record<1 | 2 | 3 | 4 | 5 | 6 | 7, number> = {
  1: 35, 2: 30, 3: 27, 4: 30, 5: 24, 6: 29, 7: 39,
};

export const WAINWRIGHT_STORAGE_KEY = "summitready_wainwrights_ticked";

export const WAINWRIGHTS: WainwrightFell[] = [
  // ── Book 1: Eastern Fells (35) ───────────────────────────────────────────────
  { id: "helvellyn",          name: "Helvellyn",           book: 1, summitElevation: 950, elevationGain: 800 },
  { id: "nethermost-pike",    name: "Nethermost Pike",      book: 1, summitElevation: 891, elevationGain: 740 },
  { id: "dollywaggon-pike",   name: "Dollywaggon Pike",     book: 1, summitElevation: 858, elevationGain: 710 },
  { id: "catstycam",          name: "Catstycam",            book: 1, summitElevation: 890, elevationGain: 730 },
  { id: "white-side",         name: "White Side",           book: 1, summitElevation: 863, elevationGain: 700 },
  { id: "raise",              name: "Raise",                book: 1, summitElevation: 883, elevationGain: 720 },
  { id: "stybarrow-dodd",     name: "Stybarrow Dodd",       book: 1, summitElevation: 843, elevationGain: 680 },
  { id: "watsons-dodd",       name: "Watson's Dodd",        book: 1, summitElevation: 789, elevationGain: 630 },
  { id: "great-dodd",         name: "Great Dodd",           book: 1, summitElevation: 857, elevationGain: 700 },
  { id: "clough-head",        name: "Clough Head",          book: 1, summitElevation: 726, elevationGain: 560 },
  { id: "birkhouse-moor",     name: "Birkhouse Moor",       book: 1, summitElevation: 718, elevationGain: 540 },
  { id: "sheffield-pike",     name: "Sheffield Pike",       book: 1, summitElevation: 675, elevationGain: 500 },
  { id: "glenridding-dodd",   name: "Glenridding Dodd",     book: 1, summitElevation: 442, elevationGain: 290 },
  { id: "seat-sandal",        name: "Seat Sandal",          book: 1, summitElevation: 736, elevationGain: 580 },
  { id: "fairfield",          name: "Fairfield",            book: 1, summitElevation: 873, elevationGain: 720 },
  { id: "great-rigg",         name: "Great Rigg",           book: 1, summitElevation: 766, elevationGain: 600 },
  { id: "heron-pike",         name: "Heron Pike",           book: 1, summitElevation: 612, elevationGain: 450 },
  { id: "nab-scar",           name: "Nab Scar",             book: 1, summitElevation: 450, elevationGain: 300 },
  { id: "stone-arthur",       name: "Stone Arthur",         book: 1, summitElevation: 500, elevationGain: 340 },
  { id: "high-pike-scandale", name: "High Pike",            book: 1, summitElevation: 656, elevationGain: 480 },
  { id: "low-pike",           name: "Low Pike",             book: 1, summitElevation: 508, elevationGain: 350 },
  { id: "arnison-crag",       name: "Arnison Crag",         book: 1, summitElevation: 433, elevationGain: 280 },
  { id: "birks",              name: "Birks",                book: 1, summitElevation: 622, elevationGain: 460 },
  { id: "st-sunday-crag",     name: "St Sunday Crag",       book: 1, summitElevation: 841, elevationGain: 680 },
  { id: "hartsop-above-how",  name: "Hartsop above How",    book: 1, summitElevation: 586, elevationGain: 420 },
  { id: "dove-crag",          name: "Dove Crag",            book: 1, summitElevation: 792, elevationGain: 630 },
  { id: "hart-crag",          name: "Hart Crag",            book: 1, summitElevation: 822, elevationGain: 660 },
  { id: "high-hartsop-dodd",  name: "High Hartsop Dodd",    book: 1, summitElevation: 519, elevationGain: 360 },
  { id: "middle-dodd",        name: "Middle Dodd",          book: 1, summitElevation: 654, elevationGain: 480 },
  { id: "little-hart-crag",   name: "Little Hart Crag",     book: 1, summitElevation: 637, elevationGain: 460 },
  { id: "red-screes",         name: "Red Screes",           book: 1, summitElevation: 776, elevationGain: 610 },
  { id: "wansfell",           name: "Wansfell",             book: 1, summitElevation: 484, elevationGain: 330 },
  { id: "troutbeck-tongue",   name: "Troutbeck Tongue",     book: 1, summitElevation: 364, elevationGain: 220 },
  { id: "ill-bell",           name: "Ill Bell",             book: 1, summitElevation: 757, elevationGain: 590 },
  { id: "yoke",               name: "Yoke",                 book: 1, summitElevation: 706, elevationGain: 540 },

  // ── Book 2: Far Eastern Fells (30) ──────────────────────────────────────────
  { id: "high-street",        name: "High Street",          book: 2, summitElevation: 828, elevationGain: 660 },
  { id: "rampsgill-head",     name: "Rampsgill Head",       book: 2, summitElevation: 792, elevationGain: 620 },
  { id: "kidsty-pike",        name: "Kidsty Pike",          book: 2, summitElevation: 780, elevationGain: 610 },
  { id: "rest-dodd",          name: "Rest Dodd",            book: 2, summitElevation: 696, elevationGain: 520 },
  { id: "the-nab",            name: "The Nab",              book: 2, summitElevation: 576, elevationGain: 400 },
  { id: "gray-crag",          name: "Gray Crag",            book: 2, summitElevation: 638, elevationGain: 460 },
  { id: "thornthwaite-crag",  name: "Thornthwaite Crag",    book: 2, summitElevation: 784, elevationGain: 610 },
  { id: "froswick",           name: "Froswick",             book: 2, summitElevation: 720, elevationGain: 550 },
  { id: "caudale-moor",       name: "Caudale Moor",         book: 2, summitElevation: 763, elevationGain: 590 },
  { id: "mardale-ill-bell",   name: "Mardale Ill Bell",     book: 2, summitElevation: 760, elevationGain: 580 },
  { id: "harter-fell-mardale",name: "Harter Fell",          book: 2, summitElevation: 778, elevationGain: 600 },
  { id: "branstree",          name: "Branstree",            book: 2, summitElevation: 713, elevationGain: 540 },
  { id: "selside-pike",       name: "Selside Pike",         book: 2, summitElevation: 655, elevationGain: 470 },
  { id: "tarn-crag-far-east", name: "Tarn Crag",            book: 2, summitElevation: 664, elevationGain: 480 },
  { id: "loadpot-hill",       name: "Loadpot Hill",         book: 2, summitElevation: 671, elevationGain: 490 },
  { id: "wether-hill",        name: "Wether Hill",          book: 2, summitElevation: 670, elevationGain: 490 },
  { id: "place-fell",         name: "Place Fell",           book: 2, summitElevation: 657, elevationGain: 470 },
  { id: "beda-fell",          name: "Beda Fell",            book: 2, summitElevation: 509, elevationGain: 340 },
  { id: "angletarn-pikes",    name: "Angletarn Pikes",      book: 2, summitElevation: 567, elevationGain: 390 },
  { id: "the-knott",          name: "The Knott",            book: 2, summitElevation: 739, elevationGain: 560 },
  { id: "high-raise-far-east",name: "High Raise",           book: 2, summitElevation: 802, elevationGain: 630 },
  { id: "hallin-fell",        name: "Hallin Fell",          book: 2, summitElevation: 388, elevationGain: 240 },
  { id: "steel-knotts",       name: "Steel Knotts",         book: 2, summitElevation: 432, elevationGain: 270 },
  { id: "arthurs-pike",       name: "Arthur's Pike",        book: 2, summitElevation: 533, elevationGain: 360 },
  { id: "bonscale-pike",      name: "Bonscale Pike",        book: 2, summitElevation: 524, elevationGain: 350 },
  { id: "sour-howes",         name: "Sour Howes",           book: 2, summitElevation: 483, elevationGain: 310 },
  { id: "sallows",            name: "Sallows",              book: 2, summitElevation: 516, elevationGain: 340 },
  { id: "kentmere-pike",      name: "Kentmere Pike",        book: 2, summitElevation: 730, elevationGain: 560 },
  { id: "shipman-knotts",     name: "Shipman Knotts",       book: 2, summitElevation: 587, elevationGain: 410 },
  { id: "great-mell-fell",    name: "Great Mell Fell",      book: 2, summitElevation: 537, elevationGain: 360 },

  // ── Book 3: Central Fells (27) ───────────────────────────────────────────────
  { id: "harrison-stickle",   name: "Harrison Stickle",     book: 3, summitElevation: 736, elevationGain: 570 },
  { id: "pike-of-stickle",    name: "Pike of Stickle",      book: 3, summitElevation: 709, elevationGain: 540 },
  { id: "loft-crag",          name: "Loft Crag",            book: 3, summitElevation: 682, elevationGain: 510 },
  { id: "thunacar-knott",     name: "Thunacar Knott",       book: 3, summitElevation: 723, elevationGain: 560 },
  { id: "high-raise-central", name: "High Raise",           book: 3, summitElevation: 762, elevationGain: 590 },
  { id: "sergeant-man",       name: "Sergeant Man",         book: 3, summitElevation: 736, elevationGain: 570 },
  { id: "pavey-ark",          name: "Pavey Ark",            book: 3, summitElevation: 700, elevationGain: 540 },
  { id: "bowfell",            name: "Bowfell",              book: 3, summitElevation: 902, elevationGain: 750 },
  { id: "esk-pike",           name: "Esk Pike",             book: 3, summitElevation: 885, elevationGain: 730 },
  { id: "allen-crags",        name: "Allen Crags",          book: 3, summitElevation: 785, elevationGain: 610 },
  { id: "glaramara",          name: "Glaramara",            book: 3, summitElevation: 783, elevationGain: 610 },
  { id: "rosthwaite-fell",    name: "Rosthwaite Fell",      book: 3, summitElevation: 612, elevationGain: 440 },
  { id: "ullscarf",           name: "Ullscarf",             book: 3, summitElevation: 726, elevationGain: 560 },
  { id: "high-seat",          name: "High Seat",            book: 3, summitElevation: 608, elevationGain: 440 },
  { id: "bleaberry-fell",     name: "Bleaberry Fell",       book: 3, summitElevation: 590, elevationGain: 420 },
  { id: "armboth-fell",       name: "Armboth Fell",         book: 3, summitElevation: 479, elevationGain: 320 },
  { id: "blea-rigg",          name: "Blea Rigg",            book: 3, summitElevation: 541, elevationGain: 370 },
  { id: "silver-how",         name: "Silver How",           book: 3, summitElevation: 395, elevationGain: 250 },
  { id: "lingmoor-fell",      name: "Lingmoor Fell",        book: 3, summitElevation: 469, elevationGain: 310 },
  { id: "wetherlam",          name: "Wetherlam",            book: 3, summitElevation: 762, elevationGain: 590 },
  { id: "pike-of-blisco",     name: "Pike of Blisco",       book: 3, summitElevation: 705, elevationGain: 540 },
  { id: "cold-pike",          name: "Cold Pike",            book: 3, summitElevation: 701, elevationGain: 530 },
  { id: "rossett-pike",       name: "Rossett Pike",         book: 3, summitElevation: 651, elevationGain: 480 },
  { id: "sergeants-crag",     name: "Sergeant's Crag",      book: 3, summitElevation: 571, elevationGain: 400 },
  { id: "eagle-crag",         name: "Eagle Crag",           book: 3, summitElevation: 525, elevationGain: 360 },
  { id: "gibson-knott",       name: "Gibson Knott",         book: 3, summitElevation: 420, elevationGain: 270 },
  { id: "helm-crag",          name: "Helm Crag",            book: 3, summitElevation: 405, elevationGain: 260 },

  // ── Book 4: Southern Fells (30) ──────────────────────────────────────────────
  { id: "scafell-pike",       name: "Scafell Pike",         book: 4, summitElevation: 978, elevationGain: 900 },
  { id: "scafell",            name: "Scafell",              book: 4, summitElevation: 964, elevationGain: 880 },
  { id: "ill-crag",           name: "Ill Crag",             book: 4, summitElevation: 935, elevationGain: 860 },
  { id: "broad-crag",         name: "Broad Crag",           book: 4, summitElevation: 934, elevationGain: 850 },
  { id: "great-end",          name: "Great End",            book: 4, summitElevation: 910, elevationGain: 840 },
  { id: "lingmell",           name: "Lingmell",             book: 4, summitElevation: 807, elevationGain: 640 },
  { id: "slight-side",        name: "Slight Side",          book: 4, summitElevation: 762, elevationGain: 590 },
  { id: "coniston-old-man",   name: "Coniston Old Man",     book: 4, summitElevation: 803, elevationGain: 630 },
  { id: "brim-fell",          name: "Brim Fell",            book: 4, summitElevation: 796, elevationGain: 620 },
  { id: "swirl-how",          name: "Swirl How",            book: 4, summitElevation: 802, elevationGain: 630 },
  { id: "great-carrs",        name: "Great Carrs",          book: 4, summitElevation: 785, elevationGain: 610 },
  { id: "gray-friar",         name: "Gray Friar",           book: 4, summitElevation: 770, elevationGain: 590 },
  { id: "dow-crag",           name: "Dow Crag",             book: 4, summitElevation: 778, elevationGain: 600 },
  { id: "brown-pike",         name: "Brown Pike",           book: 4, summitElevation: 682, elevationGain: 500 },
  { id: "harter-fell-eskdale",name: "Harter Fell (Eskdale)",book: 4, summitElevation: 649, elevationGain: 470 },
  { id: "hard-knott",         name: "Hard Knott",           book: 4, summitElevation: 549, elevationGain: 370 },
  { id: "illgill-head",       name: "Illgill Head",         book: 4, summitElevation: 609, elevationGain: 430 },
  { id: "whin-rigg",          name: "Whin Rigg",            book: 4, summitElevation: 535, elevationGain: 360 },
  { id: "buck-pike",           name: "Buck Pike",            book: 4, summitElevation: 744, elevationGain: 570 },
  { id: "corney-fell",        name: "Corney Fell",          book: 4, summitElevation: 448, elevationGain: 290 },
  { id: "great-knott",        name: "Great Knott",          book: 4, summitElevation: 696, elevationGain: 510 },
  { id: "black-combe",        name: "Black Combe",          book: 4, summitElevation: 600, elevationGain: 430 },
  { id: "stickle-pike",       name: "Stickle Pike",         book: 4, summitElevation: 375, elevationGain: 230 },
  { id: "caw",                name: "Caw",                  book: 4, summitElevation: 529, elevationGain: 350 },
  { id: "green-crag",         name: "Green Crag",           book: 4, summitElevation: 489, elevationGain: 320 },
  { id: "buckbarrow",         name: "Buckbarrow",           book: 4, summitElevation: 424, elevationGain: 270 },
  { id: "whitfell",           name: "Whitfell",             book: 4, summitElevation: 573, elevationGain: 390 },
  { id: "great-worm-crag",    name: "Great Worm Crag",      book: 4, summitElevation: 416, elevationGain: 260 },
  { id: "stainton-pike",      name: "Stainton Pike",        book: 4, summitElevation: 498, elevationGain: 330 },
  { id: "hesk-fell",          name: "Hesk Fell",            book: 4, summitElevation: 476, elevationGain: 310 },

  // ── Book 5: Northern Fells (24) ──────────────────────────────────────────────
  { id: "skiddaw",            name: "Skiddaw",              book: 5, summitElevation: 931, elevationGain: 860 },
  { id: "blencathra",         name: "Blencathra",           book: 5, summitElevation: 868, elevationGain: 800 },
  { id: "skiddaw-little-man", name: "Skiddaw Little Man",   book: 5, summitElevation: 865, elevationGain: 790 },
  { id: "carl-side",          name: "Carl Side",            book: 5, summitElevation: 746, elevationGain: 670 },
  { id: "long-side",          name: "Long Side",            book: 5, summitElevation: 734, elevationGain: 660 },
  { id: "ullock-pike",        name: "Ullock Pike",          book: 5, summitElevation: 690, elevationGain: 610 },
  { id: "bakestall",          name: "Bakestall",            book: 5, summitElevation: 673, elevationGain: 590 },
  { id: "bowscale-fell",      name: "Bowscale Fell",        book: 5, summitElevation: 702, elevationGain: 520 },
  { id: "bannerdale-crags",   name: "Bannerdale Crags",     book: 5, summitElevation: 683, elevationGain: 500 },
  { id: "souther-fell",       name: "Souther Fell",         book: 5, summitElevation: 522, elevationGain: 370 },
  { id: "great-calva",        name: "Great Calva",          book: 5, summitElevation: 690, elevationGain: 500 },
  { id: "knott",              name: "Knott",                book: 5, summitElevation: 710, elevationGain: 520 },
  { id: "high-pike-caldbeck", name: "High Pike",            book: 5, summitElevation: 658, elevationGain: 470 },
  { id: "carrock-fell",       name: "Carrock Fell",         book: 5, summitElevation: 663, elevationGain: 470 },
  { id: "great-sca-fell",     name: "Great Sca Fell",       book: 5, summitElevation: 651, elevationGain: 460 },
  { id: "little-sca-fell",    name: "Little Sca Fell",      book: 5, summitElevation: 606, elevationGain: 420 },
  { id: "meal-fell",          name: "Meal Fell",            book: 5, summitElevation: 550, elevationGain: 370 },
  { id: "great-cockup",       name: "Great Cockup",         book: 5, summitElevation: 526, elevationGain: 350 },
  { id: "longlands-fell",     name: "Longlands Fell",       book: 5, summitElevation: 483, elevationGain: 310 },
  { id: "brae-fell",          name: "Brae Fell",            book: 5, summitElevation: 586, elevationGain: 400 },
  { id: "binsey",             name: "Binsey",               book: 5, summitElevation: 447, elevationGain: 290 },
  { id: "dodd",               name: "Dodd",                 book: 5, summitElevation: 502, elevationGain: 330 },
  { id: "sale-fell",          name: "Sale Fell",            book: 5, summitElevation: 359, elevationGain: 220 },
  { id: "mungrisdale-common", name: "Mungrisdale Common",   book: 5, summitElevation: 633, elevationGain: 450 },

  // ── Book 6: North Western Fells (29) ─────────────────────────────────────────
  { id: "grisedale-pike",     name: "Grisedale Pike",       book: 6, summitElevation: 791, elevationGain: 620 },
  { id: "hopegill-head",      name: "Hopegill Head",        book: 6, summitElevation: 770, elevationGain: 600 },
  { id: "whiteside",          name: "Whiteside",            book: 6, summitElevation: 719, elevationGain: 550 },
  { id: "grasmoor",           name: "Grasmoor",             book: 6, summitElevation: 852, elevationGain: 680 },
  { id: "wandope",            name: "Wandope",              book: 6, summitElevation: 772, elevationGain: 600 },
  { id: "crag-hill",          name: "Crag Hill",            book: 6, summitElevation: 839, elevationGain: 670 },
  { id: "sail",               name: "Sail",                 book: 6, summitElevation: 773, elevationGain: 600 },
  { id: "scar-crags",         name: "Scar Crags",           book: 6, summitElevation: 672, elevationGain: 500 },
  { id: "causey-pike",        name: "Causey Pike",          book: 6, summitElevation: 637, elevationGain: 470 },
  { id: "outerside",          name: "Outerside",            book: 6, summitElevation: 568, elevationGain: 400 },
  { id: "whiteless-pike",     name: "Whiteless Pike",       book: 6, summitElevation: 660, elevationGain: 490 },
  { id: "knott-rigg",         name: "Knott Rigg",           book: 6, summitElevation: 556, elevationGain: 390 },
  { id: "ard-crags",          name: "Ard Crags",            book: 6, summitElevation: 581, elevationGain: 410 },
  { id: "dale-head",          name: "Dale Head",            book: 6, summitElevation: 753, elevationGain: 580 },
  { id: "hindscarth",         name: "Hindscarth",           book: 6, summitElevation: 727, elevationGain: 560 },
  { id: "robinson",           name: "Robinson",             book: 6, summitElevation: 737, elevationGain: 570 },
  { id: "catbells",           name: "Catbells",             book: 6, summitElevation: 451, elevationGain: 300 },
  { id: "maiden-moor",        name: "Maiden Moor",          book: 6, summitElevation: 576, elevationGain: 400 },
  { id: "high-spy",           name: "High Spy",             book: 6, summitElevation: 653, elevationGain: 480 },
  { id: "castle-crag",        name: "Castle Crag",          book: 6, summitElevation: 290, elevationGain: 180 },
  { id: "barrow",             name: "Barrow",               book: 6, summitElevation: 455, elevationGain: 300 },
  { id: "lords-seat",         name: "Lord's Seat",          book: 6, summitElevation: 552, elevationGain: 380 },
  { id: "broom-fell",         name: "Broom Fell",           book: 6, summitElevation: 511, elevationGain: 340 },
  { id: "graystones",         name: "Graystones",           book: 6, summitElevation: 452, elevationGain: 290 },
  { id: "whinlatter",         name: "Whinlatter",           book: 6, summitElevation: 525, elevationGain: 350 },
  { id: "rannerdale-knotts",  name: "Rannerdale Knotts",    book: 6, summitElevation: 355, elevationGain: 220 },
  { id: "mellbreak",          name: "Mellbreak",            book: 6, summitElevation: 512, elevationGain: 340 },
  { id: "ling-fell",          name: "Ling Fell",            book: 6, summitElevation: 373, elevationGain: 230 },
  { id: "scope-end",          name: "Scope End",            book: 6, summitElevation: 442, elevationGain: 280 },

  // ── Book 7: Western Fells (39) ───────────────────────────────────────────────
  { id: "great-gable",        name: "Great Gable",          book: 7, summitElevation: 899, elevationGain: 850 },
  { id: "green-gable",        name: "Green Gable",          book: 7, summitElevation: 801, elevationGain: 730 },
  { id: "kirk-fell",          name: "Kirk Fell",            book: 7, summitElevation: 802, elevationGain: 730 },
  { id: "brandreth",          name: "Brandreth",            book: 7, summitElevation: 715, elevationGain: 630 },
  { id: "grey-knotts",        name: "Grey Knotts",          book: 7, summitElevation: 697, elevationGain: 610 },
  { id: "base-brown",         name: "Base Brown",           book: 7, summitElevation: 646, elevationGain: 560 },
  { id: "haystacks",          name: "Haystacks",            book: 7, summitElevation: 597, elevationGain: 440 },
  { id: "high-crag",          name: "High Crag",            book: 7, summitElevation: 744, elevationGain: 570 },
  { id: "high-stile",         name: "High Stile",           book: 7, summitElevation: 806, elevationGain: 640 },
  { id: "red-pike-buttermere",name: "Red Pike (Buttermere)", book: 7, summitElevation: 755, elevationGain: 590 },
  { id: "fleetwith-pike",     name: "Fleetwith Pike",       book: 7, summitElevation: 648, elevationGain: 470 },
  { id: "pillar",             name: "Pillar",               book: 7, summitElevation: 892, elevationGain: 840 },
  { id: "looking-stead",      name: "Looking Stead",        book: 7, summitElevation: 627, elevationGain: 440 },
  { id: "scoat-fell",         name: "Scoat Fell",           book: 7, summitElevation: 841, elevationGain: 770 },
  { id: "red-pike-wasdale",   name: "Red Pike (Wasdale)",   book: 7, summitElevation: 826, elevationGain: 750 },
  { id: "haycock",            name: "Haycock",              book: 7, summitElevation: 797, elevationGain: 710 },
  { id: "caw-fell",           name: "Caw Fell",             book: 7, summitElevation: 697, elevationGain: 600 },
  { id: "steeple",            name: "Steeple",              book: 7, summitElevation: 819, elevationGain: 740 },
  { id: "starling-dodd",      name: "Starling Dodd",        book: 7, summitElevation: 633, elevationGain: 450 },
  { id: "great-borne",        name: "Great Borne",          book: 7, summitElevation: 616, elevationGain: 430 },
  { id: "hen-comb",           name: "Hen Comb",             book: 7, summitElevation: 509, elevationGain: 340 },
  { id: "gavel-fell",         name: "Gavel Fell",           book: 7, summitElevation: 526, elevationGain: 350 },
  { id: "blake-fell",         name: "Blake Fell",           book: 7, summitElevation: 573, elevationGain: 390 },
  { id: "burnbank-fell",      name: "Burnbank Fell",        book: 7, summitElevation: 475, elevationGain: 300 },
  { id: "lank-rigg",          name: "Lank Rigg",            book: 7, summitElevation: 541, elevationGain: 360 },
  { id: "crag-fell",          name: "Crag Fell",            book: 7, summitElevation: 523, elevationGain: 340 },
  { id: "whoap",              name: "Whoap",                book: 7, summitElevation: 511, elevationGain: 330 },
  { id: "iron-crag",          name: "Iron Crag",            book: 7, summitElevation: 640, elevationGain: 450 },
  { id: "grike",              name: "Grike",                book: 7, summitElevation: 488, elevationGain: 310 },
  { id: "seatallan",          name: "Seatallan",            book: 7, summitElevation: 692, elevationGain: 510 },
  { id: "middle-fell",        name: "Middle Fell",          book: 7, summitElevation: 582, elevationGain: 400 },
  { id: "yewbarrow",          name: "Yewbarrow",            book: 7, summitElevation: 628, elevationGain: 450 },
  { id: "irton-pike",         name: "Irton Pike",           book: 7, summitElevation: 159, elevationGain: 100 },
  { id: "knock-murton",       name: "Knock Murton",         book: 7, summitElevation: 449, elevationGain: 290 },
  { id: "buck-barrow",        name: "Buck Barrow",          book: 7, summitElevation: 549, elevationGain: 360 },
  { id: "black-fell",         name: "Black Fell",           book: 7, summitElevation: 323, elevationGain: 200 },
  { id: "fellbarrow",         name: "Fellbarrow",           book: 7, summitElevation: 416, elevationGain: 260 },
  { id: "low-fell",           name: "Low Fell",             book: 7, summitElevation: 423, elevationGain: 260 },
  { id: "carling-knott",      name: "Carling Knott",        book: 7, summitElevation: 544, elevationGain: 360 },
];
