import {
  buildPlacementAwarePrompt,
  type PlacementPromptInput,
} from "./promptBuilder.js";

export const BATCH_02_ID = "batch-02";
export const BATCH_02_ESTIMATED_COST_PER_MASTER = 0.04;

export interface Batch02AssetDefinition extends PlacementPromptInput {
  family: string;
  cropGuidance: string;
}

export const BATCH_02_ASSETS: Batch02AssetDefinition[] = [
  {
    assetId: "SR-EXPLORE-HERO-002",
    title: "Explore — Into the Mountains",
    family: "Explore",
    placement: "explore.discovery.hero",
    subject: "A cinematic British mountain discovery landscape with a dramatic credible ridge leading the eye into distant peaks and a deep valley.",
    focalLocation: "The route-defining ridge runs from the lower foreground toward the middle distance.",
    negativeSpaceLocation: "Generous dark, quiet sky and lower-left terrain for native discovery UI.",
    cropRequirements: "The ridge journey, distant peaks and valley depth must survive 16:9 and 4:5 mobile crops without essential detail at the extreme edges.",
    people: "No people.",
    moodWeather: "Restrained early light, realistic British mountain weather and atmospheric depth.",
    geographicIdentity: "Credible non-specific British mountain terrain; do not imply or resemble a claimed named summit.",
    exclusions: ["named-mountain claim", "fantasy peaks", "oversaturated HDR", "text", "UI", "route line"],
    cropGuidance: "Protect the ridge journey and distant peaks; preserve dark overlay space.",
  },
  {
    assetId: "SR-EXPLORE-RIDGE-002",
    title: "Explore Route — Exposed Ridge",
    family: "Explore",
    placement: "explore.route.card.ridge",
    subject: "An authentic-feeling UK high-ridge hiking scene with a strong walkable trail line, exposed terrain and layered atmospheric depth.",
    focalLocation: "Trail and ridge line travel from the lower third toward the central distance.",
    negativeSpaceLocation: "Quiet darker sky and one uncluttered side for native route-card metadata.",
    cropRequirements: "Keep the trail line and distant hiker readable in wide and portrait card crops.",
    people: "One small distant hillwalker for scale only, practical equipment, face not visible.",
    moodWeather: "Cool changing upland weather with restrained natural light.",
    geographicIdentity: "Credible generic UK high ridge with no identifiable named-mountain claim.",
    exclusions: ["named mountain", "extreme climbing", "unsafe position", "close-up face", "text", "route overlay"],
    cropGuidance: "Retain the complete trail line and small scale figure away from crop edges.",
  },
  {
    assetId: "SR-EXPLORE-SUMMIT-002",
    title: "Explore Route — Summit Day",
    family: "Explore",
    placement: "explore.route.card.summit",
    subject: "A rugged British summit approach with tactile stone and rock foreground, layered mountains and visibly changing weather.",
    focalLocation: "Rocky route foreground leading toward a plausible summit objective in the middle distance.",
    negativeSpaceLocation: "A quieter darker upper-left area for route-card UI.",
    cropRequirements: "Preserve the rocky approach and layered mountain depth in 16:9 and 4:5 crops.",
    people: "No people.",
    moodWeather: "Premium outdoor editorial realism with broken light and natural storm atmosphere.",
    geographicIdentity: "Non-specific credible British summit terrain, not a representation of a named mountain.",
    exclusions: ["named summit claim", "fantasy geology", "oversaturated light", "text", "badges", "UI"],
    cropGuidance: "Keep the foreground approach and summit objective clear across mobile crops.",
  },
  {
    assetId: "SR-EXPLORE-VALLEY-002",
    title: "Explore Route — Valley to Mountain",
    family: "Explore",
    placement: "explore.route.card.valley",
    subject: "A mountain route beginning in a green British valley and rising visibly toward imposing but plausible high ground.",
    focalLocation: "A natural trail creates a clear journey from lower valley foreground to the high ground.",
    negativeSpaceLocation: "Quiet sky and a darker valley edge for native route information.",
    cropRequirements: "The visual valley-to-mountain journey must remain readable in wide and portrait card crops.",
    people: "No people.",
    moodWeather: "Restrained natural greens, stone and blue-grey atmosphere with realistic depth.",
    geographicIdentity: "Credible non-specific British valley and mountain terrain.",
    exclusions: ["named mountain", "painted route line", "fantasy valley", "oversaturated green", "text", "UI"],
    cropGuidance: "Preserve the complete low-to-high route journey and avoid edge-dependent landmarks.",
  },
  {
    assetId: "SR-TRACK-HERO-002",
    title: "Track — Into the Wild",
    family: "Track",
    placement: "track.hero",
    subject: "A lone hillwalker moving with purpose through a rugged upland trail, with the landscape opening ahead and a strong sense of forward progress.",
    focalLocation: "Hillwalker and trail on the right third, moving away from camera.",
    negativeSpaceLocation: "Clean darker left and central terrain for GPS and tracking controls.",
    cropRequirements: "Keep the complete walker, trail direction and quiet overlay area in mobile hero crops.",
    people: "One anonymous hillwalker seen from behind, practical boots, clothing and daypack.",
    moodWeather: "Realistic cool upland weather and tactile terrain, energetic but not staged.",
    geographicIdentity: "Credible non-specific UK upland trail.",
    exclusions: ["phone in hand", "baked GPS line", "running race", "close-up face", "brand logo", "text"],
    cropGuidance: "Keep the walker secondary and preserve broad quiet overlay space.",
  },
  {
    assetId: "SR-TRACK-ACTIVITY-002",
    title: "Track — Mountain Activity",
    family: "Track",
    placement: "track.activity.hero",
    subject: "An elevated photographic view across a winding real mountain trail and varied terrain, communicating distance and accumulated elevation.",
    focalLocation: "The trail winds naturally from the lower frame through the middle distance.",
    negativeSpaceLocation: "Quiet darker terrain and sky for activity metrics.",
    cropRequirements: "Preserve the winding trail, elevation layers and useful overlay area in wide and card crops.",
    people: "No people.",
    moodWeather: "Natural subdued mountain light with realistic relief and atmospheric scale.",
    geographicIdentity: "Plausible generic mountain terrain without a named-location claim.",
    exclusions: ["drawn GPS line", "map labels", "fake route data", "fantasy terrain", "text", "UI"],
    cropGuidance: "Retain the winding trail and layered elevation without crowding the data area.",
  },
  {
    assetId: "SR-EXPEDITION-HERO-002",
    title: "Expeditions — Bigger Objective",
    family: "Expeditions",
    placement: "expedition.discovery.hero",
    subject: "A grand realistic high-mountain expedition approach with immense layered terrain and distant climbers used only for scale.",
    focalLocation: "High objective in the upper-middle distance; tiny climbers low in frame.",
    negativeSpaceLocation: "Broad darker side and sky for expedition discovery UI.",
    cropRequirements: "Keep the scale relationship, objective and safe overlay space in mobile hero crops.",
    people: "Two or three very distant climbers with plausible equipment and safe spacing.",
    moodWeather: "Dramatic but physically realistic cold atmosphere, restrained color and natural optics.",
    geographicIdentity: "Non-specific high-mountain expedition terrain; not a false representation of a named peak.",
    exclusions: ["named peak claim", "fantasy mountain", "impossible exposure", "summit celebration", "flags", "text"],
    cropGuidance: "Preserve immense scale and keep climbers small, secondary and away from edges.",
  },
  {
    assetId: "SR-EXPEDITION-STAGE-002",
    title: "Expedition — The Ascent",
    family: "Expeditions",
    placement: "expedition.stage.hero",
    subject: "Climbers ascending broad realistic mountain terrain toward a high objective, with a clear vertical journey through the frame.",
    focalLocation: "Ascending line of small climbers in the lower-middle frame leading toward the objective.",
    negativeSpaceLocation: "Clean darker side and upper sky for stage and progress UI.",
    cropRequirements: "The ascent path, climbers and objective must survive hero and card crops.",
    people: "A small distant team with plausible clothing, equipment and safe positions.",
    moodWeather: "Cold natural light, credible mountain conditions and aspirational scale without fantasy.",
    geographicIdentity: "Generic high-mountain objective with no named-peak claim.",
    exclusions: ["impossible climbing", "unsafe rope work", "fantasy peak", "close-up faces", "flags", "text"],
    cropGuidance: "Maintain the vertical journey and protected progress-overlay area.",
  },
  {
    assetId: "SR-YOU-HERO-002",
    title: "You — Mountain Identity",
    family: "You / Profile",
    placement: "profile.hero",
    subject: "An anonymous experienced hillwalker viewed from behind at a summit or ridge overlook, secondary to an expansive mountain environment.",
    focalLocation: "Person on the right third looking into the landscape.",
    negativeSpaceLocation: "Ample dark quiet left and lower-left space for identity and achievement UI.",
    cropRequirements: "Keep the full natural silhouette and environmental scale in wide and portrait crops.",
    people: "One hillwalker seen from behind with no recognisable face and practical equipment.",
    moodWeather: "Quiet earned achievement, restrained mountain light and documentary realism.",
    geographicIdentity: "Credible non-specific mountain overlook.",
    exclusions: ["recognisable face", "fashion pose", "arms-up celebration", "brand logos", "text", "badges"],
    cropGuidance: "Keep the person secondary on the right and preserve overlay space on the left.",
  },
  {
    assetId: "SR-RANK-ASCENT-002",
    title: "Rank — The Ascent",
    family: "Rank",
    placement: "rank.progress.background",
    subject: "An abstract-real photographic mountain ascent composition built from layered real ridges and elevation, with a clear upward visual rhythm.",
    focalLocation: "Layered ascent rises diagonally from lower-left toward upper-right.",
    negativeSpaceLocation: "Broad low-detail dark zones around the ascent for rank and progression overlays.",
    cropRequirements: "Retain the upward rhythm and low-detail information zones in wide and portrait crops.",
    people: "No people.",
    moodWeather: "Dark cinematic natural atmosphere with restrained highlights.",
    geographicIdentity: "Physically plausible real mountain layers, not fantasy or game art.",
    exclusions: ["glowing path", "route line", "chart", "badges", "fantasy mountain", "text"],
    cropGuidance: "Protect the diagonal ascent and calm data-overlay zones.",
  },
  {
    assetId: "SR-DNA-TERRAIN-002",
    title: "Mountain DNA — Terrain Layers",
    family: "Mountain DNA",
    placement: "mountain.dna.background",
    subject: "A highly detailed real mountain terrain and ridge composition emphasizing steepness, exposure, rock, trail and relief in clear layers.",
    focalLocation: "Terrain layers and ridge structure distributed across the middle of frame.",
    negativeSpaceLocation: "Clean darker edges and calmer sky for analytical overlays.",
    cropRequirements: "Slope transitions, exposure and terrain texture remain legible in hero and card crops.",
    people: "No people.",
    moodWeather: "Cool neutral daylight, precise natural texture and realistic atmospheric depth.",
    geographicIdentity: "Credible non-specific mixed mountain terrain.",
    exclusions: ["labels", "charts", "route line", "sci-fi network", "fantasy geology", "text"],
    cropGuidance: "Retain terrain-layer readability while keeping overlay areas visually calm.",
  },
  {
    assetId: "SR-ATMOSPHERE-002",
    title: "SummitReady — Alpine Atmosphere",
    family: "App Atmosphere",
    placement: "app.atmosphere.background",
    subject: "A flexible dark cinematic real mountain atmosphere with layered ridges, cloud and restrained light for transitions, empty states and supporting surfaces.",
    focalLocation: "A subtle distant ridge and atmospheric light away from the central overlay zone.",
    negativeSpaceLocation: "Deliberate broad low-detail dark safe zones through the centre and lower frame.",
    cropRequirements: "Atmosphere and safe zones must remain useful across wide, portrait and square crops.",
    people: "No people.",
    moodWeather: "Dark believable alpine atmosphere, natural optics and restrained cool earth tones.",
    geographicIdentity: "Non-specific plausible mountain atmosphere with no named-location claim.",
    exclusions: ["fantasy skyline", "oversaturated HDR", "dramatic lightning", "text", "logos", "UI"],
    cropGuidance: "Preserve low-detail dark safe zones across all derived crops.",
  },
];

export const BATCH_02_PROMPTS = BATCH_02_ASSETS.map((asset) => ({
  ...asset,
  ...buildPlacementAwarePrompt(asset),
}));

export function validateBatch02InitialGeneration(priorAttemptCount: number): 1 {
  if (priorAttemptCount > 0) {
    throw new Error("Batch 02 permits exactly one initial generation attempt per asset");
  }
  return 1;
}