// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/summit-landing-redesign/Redesign.tsx": () => import("../components/mockups/summit-landing-redesign/Redesign.tsx"),
  "./components/mockups/summit-ui/AlpineLight.tsx": () => import("../components/mockups/summit-ui/AlpineLight.tsx"),
  "./components/mockups/summit-ui/NightTrail.tsx": () => import("../components/mockups/summit-ui/NightTrail.tsx"),
  "./components/mockups/summit-ui/PaywallMockup.tsx": () => import("../components/mockups/summit-ui/PaywallMockup.tsx"),
  "./components/mockups/summit-ui/SavedHikes.tsx": () => import("../components/mockups/summit-ui/SavedHikes.tsx"),
  "./components/mockups/summit-ui/SummitRefined.tsx": () => import("../components/mockups/summit-ui/SummitRefined.tsx"),
  "./components/mockups/summitready-explore/AchievementConstellation.tsx": () => import("../components/mockups/summitready-explore/AchievementConstellation.tsx"),
  "./components/mockups/summitready-explore/AchievementFieldJournal.tsx": () => import("../components/mockups/summitready-explore/AchievementFieldJournal.tsx"),
  "./components/mockups/summitready-explore/AchievementJourneyMap.tsx": () => import("../components/mockups/summitready-explore/AchievementJourneyMap.tsx"),
  "./components/mockups/summitready-explore/AchievementSummitCabinet.tsx": () => import("../components/mockups/summitready-explore/AchievementSummitCabinet.tsx"),
  "./components/mockups/summitready-explore/ApprovedReference.tsx": () => import("../components/mockups/summitready-explore/ApprovedReference.tsx"),
  "./components/mockups/summitready-explore/EditorialCinematicPortrait.tsx": () => import("../components/mockups/summitready-explore/EditorialCinematicPortrait.tsx"),
  "./components/mockups/summitready-explore/EditorialDocumentaryDispatch.tsx": () => import("../components/mockups/summitready-explore/EditorialDocumentaryDispatch.tsx"),
  "./components/mockups/summitready-explore/EditorialSeasonalCampaign.tsx": () => import("../components/mockups/summitready-explore/EditorialSeasonalCampaign.tsx"),
  "./components/mockups/summitready-explore/EditorialTopographicStory.tsx": () => import("../components/mockups/summitready-explore/EditorialTopographicStory.tsx"),
  "./components/mockups/summitready-explore/RankAlpineAscent.tsx": () => import("../components/mockups/summitready-explore/RankAlpineAscent.tsx"),
  "./components/mockups/summitready-explore/RankExpeditionLeague.tsx": () => import("../components/mockups/summitready-explore/RankExpeditionLeague.tsx"),
  "./components/mockups/summitready-explore/RankMountainLineage.tsx": () => import("../components/mockups/summitready-explore/RankMountainLineage.tsx"),
  "./components/mockups/summitready-explore/RankTrailPatches.tsx": () => import("../components/mockups/summitready-explore/RankTrailPatches.tsx")
};
