// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/summit-ui/AlpineLight.tsx": () => import("../components/mockups/summit-ui/AlpineLight.tsx"),
  "./components/mockups/summit-ui/NightTrail.tsx": () => import("../components/mockups/summit-ui/NightTrail.tsx"),
  "./components/mockups/summit-ui/SummitRefined.tsx": () => import("../components/mockups/summit-ui/SummitRefined.tsx")
};
