/**
 * Which summits a map draws, and what a pin may claim about them.
 *
 * Built against the Summit Data Engine catalogue, `public.mountains`: 21,792
 * rows, every one carrying a PostGIS point, read through the engine's
 * read-only pool. Not `canonical_hills`, which holds no rows at all.
 *
 * WHICH ONES. Drawing 21,792 pins at national zoom is unreadable and several
 * megabytes over mobile data. So the map thins them as you pull back — but by
 * prominence and classification rather than height, because height is a poor
 * measure of whether a hill is worth seeing. A 900 m shoulder of a bigger
 * mountain is not a destination; a 600 m isolated hill often is. Prominence
 * says which is which, and the DoBIH classifications say it even better: at
 * the scale where somebody is scanning a whole country, Munros and Wainwrights
 * are exactly what they are looking for.
 *
 * WHAT A PIN SAYS. Name, height, where it is, and what list it belongs to.
 * Not ascent — see the note on that below, because its absence is the single
 * most important thing to understand about this data.
 *
 * Pure. No database, no network. The caller fetches rows; this decides what
 * may be drawn and what may be said.
 */

/* ── Which summits a zoom shows ─────────────────────────────────────────── */

/** Below this the map draws no pins. At that scale they are a smear over a
 *  country outline, and nobody picks a hill out of it. */
export const MIN_PIN_ZOOM = 7;

/** At and above this, every summit in the rectangle is drawn. */
export const ALL_SUMMITS_ZOOM = 13;

/**
 * The named lists worth showing when the whole country is on screen.
 *
 * Roughly 720 hills between them — few enough to read, and the ones somebody
 * zoomed this far out is actually looking for.
 */
export const HEADLINE_CLASSES = ["M", "C", "W"] as const;

/**
 * The prominence that earns a pin at the widest zoom regardless of list.
 *
 * Without this the widest band is blank over most of the country. Munros and
 * Corbetts are Scottish and Wainwrights are Lake District, so Wales, Ireland,
 * the Peak District and Dartmoor would show nothing at all — Yr Wyddfa absent
 * from a map of Britain, which is indefensible.
 *
 * 500 m of prominence is a high bar that no classification covers: it catches
 * Yr Wyddfa, Scafell Pike, Carrauntoohil and the handful of others that any
 * map of these islands has to show.
 */
export const HEADLINE_PROMINENCE_M = 500;

/** Prominence in metres for a Marilyn and a HuMP, which is what those
 *  classifications mean rather than numbers chosen here. */
export const MARILYN_PROMINENCE_M = 150;
export const HUMP_PROMINENCE_M = 100;

export type PinFilter =
  /** Draw nothing. */
  | { kind: "none" }
  /** Hills on one of these lists, OR standing this proud. Either qualifies:
   *  the lists cover the famous Scottish and Lakeland hills, the prominence
   *  covers everywhere those lists do not reach. */
  | { kind: "headline"; codes: readonly string[]; minProminenceM: number }
  /** Only hills standing at least this proud of their surroundings. */
  | { kind: "prominence"; minProminenceM: number }
  /** Everything in the rectangle. */
  | { kind: "all" };

/**
 * What to draw at a given zoom.
 *
 * Returned as a description rather than a SQL fragment so the ladder can be
 * read, tested and argued with in one place, without a query in the way.
 */
export function filterForZoom(zoom: number): PinFilter {
  if (!Number.isFinite(zoom) || zoom < MIN_PIN_ZOOM) return { kind: "none" };
  if (zoom >= ALL_SUMMITS_ZOOM) return { kind: "all" };
  if (zoom >= 12) return { kind: "prominence", minProminenceM: 30 };
  if (zoom >= 10) return { kind: "prominence", minProminenceM: HUMP_PROMINENCE_M };
  if (zoom >= 9) return { kind: "prominence", minProminenceM: MARILYN_PROMINENCE_M };
  return { kind: "headline", codes: HEADLINE_CLASSES, minProminenceM: HEADLINE_PROMINENCE_M };
}

/**
 * A short name for the band a zoom falls in.
 *
 * The map uses it to notice that zooming changed which hills qualify, even
 * when the rectangle has not moved. Derived from the ladder above rather than
 * restated, so the two cannot drift apart.
 */
export function zoomBandKey(zoom: number): string {
  const filter = filterForZoom(zoom);
  switch (filter.kind) {
    case "none":       return "none";
    case "all":        return "all";
    case "headline":   return `headline:${filter.minProminenceM}`;
    case "prominence": return `prominence:${filter.minProminenceM}`;
  }
}

/**
 * The ladder as a table the browser can read: the lowest zoom at which each
 * band starts, widest zoom last. Generated by asking `filterForZoom`, so a
 * change to the ladder reaches the map without anybody editing a second copy.
 */
export function zoomBandTable(): Array<[number, string]> {
  /* Ascending, so each band is recorded at the LOWEST zoom it covers. Walking
     down instead records the highest, and then a zoom in the middle of a band
     matches no row and falls through to the band below — the map quietly shows
     the wrong hills and nothing looks broken. */
  const lowest = new Map<string, number>();
  for (let zoom = 0; zoom <= 22; zoom += 1) {
    const key = zoomBandKey(zoom);
    if (!lowest.has(key)) lowest.set(key, zoom);
  }
  return [...lowest.entries()]
    .map(([key, zoom]): [number, string] => [zoom, key])
    .sort((a, b) => b[0] - a[0]);
}

/**
 * The most pins one view may return.
 *
 * A limit the client can count on matters more than its exact value: an
 * unbounded query over a dense area is how a map becomes unusable on a slow
 * connection. Tightest zoomed out, where a careless rectangle covers Britain.
 */
export function pinCap(zoom: number): number {
  if (!Number.isFinite(zoom) || zoom < MIN_PIN_ZOOM) return 0;
  if (zoom >= ALL_SUMMITS_ZOOM) return 1500;
  if (zoom >= 10) return 800;
  return 400;
}

/* ── Classifications ────────────────────────────────────────────────────── */

/**
 * DoBIH codes to words.
 *
 * Codes are stored raw, and a hill usually carries several. A trailing "="
 * marks a tied top — the same classification, so it is read as the base code
 * rather than treated as unknown and dropped.
 */
const CLASS_NAMES: Record<string, string> = {
  M:  "Munro",
  MT: "Munro Top",
  C:  "Corbett",
  W:  "Wainwright",
  WO: "Wainwright Outlying Fell",
  D:  "Donald",
  Ma: "Marilyn",
  Hu: "HuMP",
};

/**
 * Which one to put on the pin when a hill is on several lists.
 *
 * Ben Nevis carries eight codes. Only one fits on a pin, and it should be the
 * one that means something to a walker: "Munro" tells them more than "Sim".
 * Most specific and best known first.
 */
const CLASS_PRECEDENCE = ["M", "C", "W", "D", "MT", "WO", "Ma", "Hu"] as const;

/**
 * The lists a walker recognises, and the only ones that earn a badge.
 *
 * Marilyn and HuMP are left out deliberately. They are real classifications
 * and the map uses their prominence thresholds to decide what to draw, but as
 * a label on a pin they mislead: almost every Welsh hill and most English ones
 * outside the Lake District are Marilyns, so Snowdon would be badged "Marilyn"
 * — a word that tells the average walker less than nothing, on the most famous
 * mountain in Wales.
 *
 * The consequence is deliberate and worth stating: Snowdon gets no badge, and
 * a minor Scottish hill gets "Munro". That is an honest reflection of the
 * data, because the named lists really are regional. A pin reading
 * "Snowdon · 1,085 m · Gwynedd, Wales" says everything it needs to.
 */
const BADGED_CLASSES = new Set(["M", "C", "W", "D", "MT", "WO"]);

/** Strips the tied-top marker so "Ma=" reads as a Marilyn. */
export function baseClassCode(code: string): string {
  return code.trim().replace(/=+$/, "");
}

/**
 * The single label a pin shows, or null when a hill is on no list worth
 * naming. Null rather than "Unclassified", which tells nobody anything.
 */
export function classificationLabel(codes: readonly string[]): string | null {
  const held = new Set(codes.map(baseClassCode));
  for (const code of CLASS_PRECEDENCE) {
    if (held.has(code) && BADGED_CLASSES.has(code)) return CLASS_NAMES[code]!;
  }
  return null;
}

/* ── Names ──────────────────────────────────────────────────────────────── */

export interface SummitName { name: string; alternative: string | null }

/**
 * A subsidiary top, rather than a second name for the same hill.
 *
 * DoBIH uses the same dash for both: "Snowdon - Yr Wyddfa" is one mountain
 * under two names, but "Beinn Dearg - South Top" is a different summit
 * altogether. Splitting the second would put a pin labelled "Beinn Dearg" on
 * a top that is not Beinn Dearg, two of them side by side with the same name,
 * and nobody looking at the map could tell which was the mountain.
 *
 * So the test is deliberately narrow: only a trailing "Top" blocks the split.
 * Being too cautious leaves a name joined up, which is untidy. Being too eager
 * mislabels a summit, which is a lie on a map.
 */
const SUBSIDIARY_TOP = /\bTop$/i;

/**
 * DoBIH writes a second name two ways: in brackets, "Ben Nevis [Beinn
 * Nibheis]", and after a dash, "Snowdon - Yr Wyddfa".
 *
 * Shown raw either reads like a formatting fault, and the Welsh or Gaelic name
 * deserves better than to be stuck behind punctuation. Split apart, the pin
 * shows one and the card can show both.
 *
 * The dash has to be a separator rather than part of a name, so it must have
 * space around it: Pen-y-ghent keeps its hyphens.
 */
export function splitName(raw: string): SummitName {
  const trimmed = raw.trim();

  const bracketed = /^(.*?)\s*\[([^\]]+)\]\s*$/.exec(trimmed);
  if (bracketed) {
    const name = bracketed[1]!.trim();
    const alternative = bracketed[2]!.trim();
    if (!name) return { name: alternative, alternative: null };
    return { name, alternative: alternative || null };
  }

  /* Hyphen, en dash or em dash, with whitespace on both sides. Only the first
     one splits: a name with two is not two alternatives. */
  const dashed = /^(.+?)\s+[-–—]\s+(.+)$/.exec(trimmed);
  if (dashed) {
    const name = dashed[1]!.trim();
    const alternative = dashed[2]!.trim();
    if (name && alternative && !SUBSIDIARY_TOP.test(alternative)) {
      return { name, alternative };
    }
  }

  return { name: trimmed, alternative: null };
}

/* ── Ascent ─────────────────────────────────────────────────────────────── */

/**
 * There is no summit ascent figure in this catalogue, and there is no honest
 * way to invent one.
 *
 * `prominence_m` is not it. Prominence is how far a summit stands above the
 * lowest col connecting it to higher ground — a fact about the landscape, not
 * about any walk. Ben Nevis has 1,344 m of prominence and no route up it
 * climbs that, because nobody starts at sea level in the col.
 *
 * Route ascent does exist, in `route_facts.total_ascent_m`, and today it holds
 * 23 rows against 21,792 mountains. So for virtually every summit the true
 * answer is "not known", and the pin says nothing rather than borrowing a
 * number that means something else.
 */
export type AscentDisplay =
  | { kind: "known"; metres: number; routeName: string | null }
  | { kind: "unknown" };

export function ascentDisplay(totalAscentM: number | null | undefined, routeName?: string | null): AscentDisplay {
  if (typeof totalAscentM !== "number" || !Number.isFinite(totalAscentM) || totalAscentM <= 0) {
    return { kind: "unknown" };
  }
  return { kind: "known", metres: Math.round(totalAscentM), routeName: routeName?.trim() || null };
}

/** The ascent line on a card, or null when there is nothing honest to say. */
export function ascentLabel(ascent: AscentDisplay): string | null {
  if (ascent.kind === "unknown") return null;
  return ascent.routeName
    ? `${ascent.metres} m of climbing via ${ascent.routeName}`
    : `${ascent.metres} m of climbing`;
}

/* ── Rows to pins ───────────────────────────────────────────────────────── */

export interface MountainRow {
  id: string;
  name: string;
  latitude: number | null;
  longitude: number | null;
  elevationM: number | null;
  prominenceM: number | null;
  country: string | null;
  region: string | null;
  county: string | null;
  classificationCodes?: readonly string[];
  totalAscentM?: number | null;
}

export interface SummitPin {
  /** The catalogue UUID. The mountain page takes this as `catalogueId`, so a
   *  pin can open it without any join. */
  id: string;
  name: string;
  alternativeName: string | null;
  lat: number;
  lng: number;
  heightM: number | null;
  prominenceM: number | null;
  /** "Munro", "Wainwright", or null. */
  classification: string | null;
  /** "Highland, Scotland" and the like, or null. */
  place: string | null;
  ascent: AscentDisplay;
}

/**
 * Where it is, in the words somebody would use.
 *
 * DoBIH regions are catalogue strings like "04A: Fort William to Loch Treig &
 * Loch Leven" — precise, and not how anyone describes where they walked. The
 * county reads better, so it leads, with the region kept only when there is
 * no county.
 */
export function placeLabel(row: Pick<MountainRow, "county" | "region" | "country">): string | null {
  const clean = (v: string | null | undefined): string | null => {
    const t = typeof v === "string" ? v.trim() : "";
    return t.length > 0 ? t : null;
  };
  const county = clean(row.county);
  const region = clean(row.region);
  const country = clean(row.country);
  /* A DoBIH region code reads as a catalogue reference, not a place. */
  const usableRegion = region && !/^\d/.test(region) ? region : null;
  const local = county ?? usableRegion;
  if (!local && !country) return null;
  if (!local) return country;
  if (!country) return local;
  if (local.toLowerCase() === country.toLowerCase()) return country;
  return `${local}, ${country}`;
}

/**
 * A row becomes a pin, or it does not.
 *
 * Every row in this catalogue has a point today, but a row without one is
 * dropped rather than placed at a default. At 0,0 a Scottish mountain appears
 * in the Atlantic off Africa.
 */
export function toPin(row: MountainRow): SummitPin | null {
  const { latitude: lat, longitude: lng } = row;
  if (typeof lat !== "number" || typeof lng !== "number") return null;
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null;
  if (lat < -90 || lat > 90 || lng < -180 || lng > 180) return null;
  if (!row.id || !row.name?.trim()) return null;

  const { name, alternative } = splitName(row.name);
  const round = (v: number | null | undefined): number | null =>
    typeof v === "number" && Number.isFinite(v) && v > 0 ? Math.round(v) : null;

  return {
    id: row.id,
    name,
    alternativeName: alternative,
    lat,
    lng,
    heightM: round(row.elevationM),
    /* Zero prominence is real — a col height of 0 appears in the data — so it
       is kept apart from missing rather than rounded away. */
    prominenceM: typeof row.prominenceM === "number" && Number.isFinite(row.prominenceM)
      ? Math.round(row.prominenceM) : null,
    classification: classificationLabel(row.classificationCodes ?? []),
    place: placeLabel(row),
    ascent: ascentDisplay(row.totalAscentM),
  };
}

/* ── The rectangle ──────────────────────────────────────────────────────── */

export interface BBox { minLat: number; maxLat: number; minLng: number; maxLng: number }

/** "minLng,minLat,maxLng,maxLat" — the order every mapping tool writes, so a
 *  caller can pass what its map gave it without rearranging and getting it
 *  wrong. */
export function parseBBox(raw: unknown): BBox | null {
  if (typeof raw !== "string") return null;
  const parts = raw.split(",").map(p => Number(p.trim()));
  if (parts.length !== 4 || parts.some(n => !Number.isFinite(n))) return null;
  const [minLng, minLat, maxLng, maxLat] = parts as [number, number, number, number];
  if (minLat < -90 || maxLat > 90 || minLng < -180 || maxLng > 180) return null;
  if (minLat >= maxLat || minLng >= maxLng) return null;
  return { minLat, maxLat, minLng, maxLng };
}

/**
 * A rectangle grown by a margin in degrees of latitude.
 *
 * The map asks for more than it shows, so a short pan does not leave a blank
 * band while a new request is in flight. Longitude widens by the same ground
 * distance, which is more degrees the further north you are — at Cape Wrath a
 * degree of longitude covers barely half what it does at the equator.
 */
export function padBBox(box: BBox, marginDeg: number): BBox {
  const midLat = (box.minLat + box.maxLat) / 2;
  const cos = Math.max(0.05, Math.cos((midLat * Math.PI) / 180));
  const lngMargin = marginDeg / cos;
  return {
    minLat: Math.max(-90, box.minLat - marginDeg),
    maxLat: Math.min(90, box.maxLat + marginDeg),
    minLng: Math.max(-180, box.minLng - lngMargin),
    maxLng: Math.min(180, box.maxLng + lngMargin),
  };
}
